# ***Computer Problems***

## First: **Matrix Powers by Numpy in Python**

$
\begin{array}{l}
A=\left\lbrack \begin{array}{cc}
0 & 1\\
1 & 1
\end{array}\right\rbrack \Rightarrow A^k =\left\lbrack \begin{array}{cc}
a & b\\
c & d
\end{array}\right\rbrack \Rightarrow A^k A=A^{k+1} =\left\lbrack \begin{array}{cc}
c & d\\
a+c & b+d 
\end{array}\right\rbrack \Rightarrow \left(\left\lbrack \begin{array}{cc}
a & b\\
c & d
\end{array}\right\rbrack \to \left\lbrack \begin{array}{cc}
c & d\\
a+c & b+d
\end{array}\right\rbrack \right)\Rightarrow A^n =\left\lbrack \begin{array}{cc}
\mathrm{fibo}\left(n\right) & \mathrm{fibo}\left(n+1\right)\\
\mathrm{fibo}\left(n+1\right) & \mathrm{fibo}\left(n+2\right)
\end{array}\right\rbrack \\
\mathrm{fibo}\left(n\right)=\left\lbrace \begin{array}{ll}
n & n=0,1\\
\mathrm{fibo}\left(n-1\right)+\mathrm{fibo}\left(n-2\right) & n\not= 0,1
\end{array}\right.
\end{array}
$

</br>
Multiply A by power n of A makes a recursive patterns for A power of n matrix, this patterns is fibonacci pattern.

In [ ]:
import numpy as np

A = np.array([[0, 1], [1, 1]])

print("A ")
print(A)
print()

for i in range(1, 8):
    Ai = np.linalg.matrix_power(A, i)
    print("A ^", i)
    print(Ai)
    print()


A 
[[0 1]
 [1 1]]

A ^ 1
[[0 1]
 [1 1]]

A ^ 2
[[1 1]
 [1 2]]

A ^ 3
[[1 2]
 [2 3]]

A ^ 4
[[2 3]
 [3 5]]

A ^ 5
[[3 5]
 [5 8]]

A ^ 6
[[ 5  8]
 [ 8 13]]

A ^ 7
[[ 8 13]
 [13 21]]



## Second: **Finding 10th power of A**